spring:
  application:
    name: microservice-commandes
  cloud:
    config:
      discovery:
        enabled: false
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 12345678
  server:
    port: 8081
